### ISSUE TITLE
Change to Coc Highlight

### ISSUE THREAD

**Issue by jrwrigh** [crusoexia/vim-monokai#40]
FYI, I'm not a huge fan of the change to the highlight color in 65fa0678d8426ae2cc7a4c42a8f0d72bde2a7bbe. I use `coc-highlight`, which ends up meaning that instead of the highlight-under-cursor being minimal (ie. easily ignored when I don't want it):
![image](https://user-images.githubusercontent.com/20801821/115584809-50d01c00-a288-11eb-9762-f39bcb01f8c7.png)
it's now the same color as builtin Python functions (float in this case).
![image](https://user-images.githubusercontent.com/20801821/115583371-11550000-a287-11eb-958d-a600eb42a38f.png)

I'd be more in favor in making the background highlight a bit more substantial:
- - `call s:h("CocHighlightText",        { "bg": s:lightblack3 })`
![image](https://user-images.githubusercontent.com/20801821/115588222-c12c6c80-a28b-11eb-9dea-9b45ab826ade.png)

- `call s:h("CocHighlightText",        { "bg": s:lightgrey })`
![image](https://user-images.githubusercontent.com/20801821/115587574-0f8d3b80-a28b-11eb-9c84-9b6c22be386c.png)

- `call s:h("CocHighlightText",        { "bg": s:warmgrey })`
    ![image](https://user-images.githubusercontent.com/20801821/115587013-6ba39000-a28a-11eb-8007-2cc831c07302.png)
- `call s:h("CocHighlightText",        { "bg": s:darkgrey })`
![image](https://user-images.githubusercontent.com/20801821/115587251-b2918580-a28a-11eb-84ae-acb6d7f8a003.png)

or in changing the foreground color to not be as bright/distracting (and also ensure that it's different than a standard syntax highlight color):
- ` call s:h("CocHighlightText",        { "fg": s:cyan })`
    ![image](https://user-images.githubusercontent.com/20801821/115586497-e28c5900-a289-11eb-8bf2-2fb4f12b053e.png)
**Note: this does require adding a "cterm" definition to  `s:cyan`:
```
let s:cyan        = { "gui": "#A1EFE4", "cterm": "NONE" }
```

Thoughts?

**Comment by crusoexia** [comment]
@jrwrigh I cannot remember why I added that line, maybe because I haven't use `coc-highlight` and that line doesn't have any effect in my local then I committed it by accident...

Thanks to your issue, now I want to give `coc-highlight` a try.

For the last option of your proposal, it is a little against my original thoughts to use the pure foreground highlights. The original thoughts to use the pure foreground color highlights are only for the language syntax only, to differentiate with the tools assists highlight which usually has background highlight or have formats like underscore.

For this case, how about to just keep the cursor-hovered word's original color, but instead let's give them a __bold__ or __underline__ effects? Your other proposals are also good, lets find out a best to make our daily life more comfortable. I will try some combinations too and will let you know the results.

**Comment by crusoexia** [comment]
If that accident commit bother you a lot, you can submit a pr to remove that line first.

**Comment by jrwrigh** [comment]
I'd be ok with just removing the commit and going back to original behavior. I'll go ahead and submit that PR. 

I agree that changing foreground color should only be for language syntax (hence why I rose the issue). I gave the other options assuming that the commit wasn't an accident.
