### ISSUE TITLE
C syntax highlighting is different between vscode and vim

### ISSUE THREAD

**Issue by huyhoang8398** [crusoexia/vim-monokai#43]
In vim, they won't highlight the function

![image](https://user-images.githubusercontent.com/25379882/162195220-742dc064-bb7e-450b-8857-bf37bd516987.png)

**Comment by crusoexia** [comment]
What's the go-to syntax highlight vim plugin do the C developers use? I almost don't use C in my daily work. 

`vim-monokai` is a color-theme plugin, itself doesn't responsible for certain language's syntax analyses, but it can rely on them. For example this color theme works well for JavaScript because it cooperates with the famous JavaScript syntax highlighting plugin [vim-javascript](git@github.com:crusoexia/FEE-weekly.git).

Currently this color-theme only designed with the built-in C syntax plugin, if there is any "standard" syntax plugin for C, I could make the color-theme compatible with it.

**Comment by jrwrigh** [comment]
I currently use CoC for my C work, which I believe does syntax highlighting(?). `vim-monokai` works quite well with it (though I'm sure there could be improvements):

![image](https://user-images.githubusercontent.com/20801821/162633590-8c4b0aad-b1eb-4dc3-9353-dff587d75e89.png)

**Comment by crusoexia** [comment]
@jrwrigh I don't think it is because of `coc.vim`, there is not any `c` syntax file there. The `highlight.vim` file is for other stuffs.
<img width="261" alt="image" src="https://user-images.githubusercontent.com/5928754/162734534-d0dd3a78-840c-49e0-a201-f84f3f826667.png">

**Comment by crusoexia** [comment]
Close as no more activity on this.

**Comment by jrwrigh** [comment]
> I currently use CoC for my C work, which I believe does syntax highlighting(?).

I believe I was referring to CoC's semantic highlighting, for what it's worth.
